// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Instrument        string         `json:"instrument"`
	Quantity          pgtype.Numeric `json:"quantity"`
	RemainingQuantity pgtype.Numeric `json:"remaining_quantity"`
	Price             pgtype.Numeric `json:"price"`
	Side              string         `json:"side"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type Trade struct {
	ID          uuid.UUID      `json:"id"`
	BuyOrderID  uuid.UUID      `json:"buy_order_id"`
	SellOrderID uuid.UUID      `json:"sell_order_id"`
	Instrument  string         `json:"instrument"`
	Quantity    pgtype.Numeric `json:"quantity"`
	Price       pgtype.Numeric `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WalletAsset struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Instrument pgtype.Text    `json:"instrument"`
	Quantity   pgtype.Numeric `json:"quantity"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
