// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET
  status = 'cancelled',
  updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status IN ('open', 'partially_filled')
RETURNING id, user_id, instrument, quantity, remaining_quantity, price, side, status
`

type CancelOrderParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type CancelOrderRow struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Instrument        string         `json:"instrument"`
	Quantity          pgtype.Numeric `json:"quantity"`
	RemainingQuantity pgtype.Numeric `json:"remaining_quantity"`
	Price             pgtype.Numeric `json:"price"`
	Side              string         `json:"side"`
	Status            string         `json:"status"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (CancelOrderRow, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.UserID)
	var i CancelOrderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Instrument,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Price,
		&i.Side,
		&i.Status,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, instrument, quantity, remaining_quantity, price, side)
VALUES ($1, $2, $3, $3, $4, $5)
RETURNING id, user_id, instrument, quantity, remaining_quantity, price, side, status
`

type CreateOrderParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Instrument string         `json:"instrument"`
	Quantity   pgtype.Numeric `json:"quantity"`
	Price      pgtype.Numeric `json:"price"`
	Side       string         `json:"side"`
}

type CreateOrderRow struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Instrument        string         `json:"instrument"`
	Quantity          pgtype.Numeric `json:"quantity"`
	RemainingQuantity pgtype.Numeric `json:"remaining_quantity"`
	Price             pgtype.Numeric `json:"price"`
	Side              string         `json:"side"`
	Status            string         `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Instrument,
		arg.Quantity,
		arg.Price,
		arg.Side,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Instrument,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Price,
		&i.Side,
		&i.Status,
	)
	return i, err
}

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (buy_order_id, sell_order_id, instrument, quantity, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTradeParams struct {
	BuyOrderID  uuid.UUID      `json:"buy_order_id"`
	SellOrderID uuid.UUID      `json:"sell_order_id"`
	Instrument  string         `json:"instrument"`
	Quantity    pgtype.Numeric `json:"quantity"`
	Price       pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.BuyOrderID,
		arg.SellOrderID,
		arg.Instrument,
		arg.Quantity,
		arg.Price,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const decrementOrderRemaining = `-- name: DecrementOrderRemaining :one
UPDATE orders
SET
  remaining_quantity = remaining_quantity - $2,
  status = CASE
    WHEN remaining_quantity - $2 = 0 THEN 'filled'
    WHEN remaining_quantity - $2 < quantity THEN 'partially_filled'
    ELSE 'open'
  END,
  updated_at = now()
WHERE id = $1
  AND remaining_quantity >= $2
RETURNING id, user_id, instrument, quantity, remaining_quantity, price, side, status
`

type DecrementOrderRemainingParams struct {
	ID                uuid.UUID      `json:"id"`
	RemainingQuantity pgtype.Numeric `json:"remaining_quantity"`
}

type DecrementOrderRemainingRow struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	Instrument        string         `json:"instrument"`
	Quantity          pgtype.Numeric `json:"quantity"`
	RemainingQuantity pgtype.Numeric `json:"remaining_quantity"`
	Price             pgtype.Numeric `json:"price"`
	Side              string         `json:"side"`
	Status            string         `json:"status"`
}

func (q *Queries) DecrementOrderRemaining(ctx context.Context, arg DecrementOrderRemainingParams) (DecrementOrderRemainingRow, error) {
	row := q.db.QueryRow(ctx, decrementOrderRemaining, arg.ID, arg.RemainingQuantity)
	var i DecrementOrderRemainingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Instrument,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Price,
		&i.Side,
		&i.Status,
	)
	return i, err
}

const findBuyMatchForSell = `-- name: FindBuyMatchForSell :one
SELECT
  id,
  user_id,
  instrument,
  quantity,
  remaining_quantity,
  price,
  side,
  status,
  created_at,
  updated_at
FROM orders
WHERE instrument = $1
  AND side = 'buy'
  AND status IN ('open', 'partially_filled')
  AND remaining_quantity > 0
  AND price >= $2
  AND user_id <> $3
ORDER BY price DESC, created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type FindBuyMatchForSellParams struct {
	Instrument string         `json:"instrument"`
	Price      pgtype.Numeric `json:"price"`
	UserID     uuid.UUID      `json:"user_id"`
}

func (q *Queries) FindBuyMatchForSell(ctx context.Context, arg FindBuyMatchForSellParams) (Order, error) {
	row := q.db.QueryRow(ctx, findBuyMatchForSell, arg.Instrument, arg.Price, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Instrument,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Price,
		&i.Side,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSellMatchForBuy = `-- name: FindSellMatchForBuy :one
SELECT
  id,
  user_id,
  instrument,
  quantity,
  remaining_quantity,
  price,
  side,
  status,
  created_at,
  updated_at
FROM orders
WHERE instrument = $1
  AND side = 'sell'
  AND status IN ('open', 'partially_filled')
  AND remaining_quantity > 0
  AND price <= $2
  AND user_id <> $3
ORDER BY price ASC, created_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type FindSellMatchForBuyParams struct {
	Instrument string         `json:"instrument"`
	Price      pgtype.Numeric `json:"price"`
	UserID     uuid.UUID      `json:"user_id"`
}

func (q *Queries) FindSellMatchForBuy(ctx context.Context, arg FindSellMatchForBuyParams) (Order, error) {
	row := q.db.QueryRow(ctx, findSellMatchForBuy, arg.Instrument, arg.Price, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Instrument,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Price,
		&i.Side,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderBookByInstrument = `-- name: GetOrderBookByInstrument :many
SELECT
  id,
  user_id,
  instrument,
  quantity,
  remaining_quantity,
  price,
  side,
  status,
  created_at,
  updated_at
FROM orders
WHERE instrument = $1
ORDER BY
  side,
  CASE WHEN side = 'buy' THEN price END DESC,
  CASE WHEN side = 'sell' THEN price END ASC,
  created_at ASC
`

func (q *Queries) GetOrderBookByInstrument(ctx context.Context, instrument string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrderBookByInstrument, instrument)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Instrument,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Price,
			&i.Side,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByUserId = `-- name: GetOrderByUserId :many
SELECT
  id,
  user_id,
  instrument,
  quantity,
  remaining_quantity,
  price,
  side,
  status,
  created_at,
  updated_at
FROM orders
WHERE user_id = $1
ORDER BY instrument
`

func (q *Queries) GetOrderByUserId(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrderByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Instrument,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Price,
			&i.Side,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
  id,
  user_id,
  instrument,
  quantity,
  remaining_quantity,
  price,
  side,
  status,
  created_at,
  updated_at
FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Instrument,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Price,
			&i.Side,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
