// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package pg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletAsset = `-- name: CreateWalletAsset :one
INSERT INTO wallet_assets (user_id, instrument, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, instrument)
DO UPDATE SET
  quantity = wallet_assets.quantity + EXCLUDED.quantity,
  updated_at = now()
RETURNING id
`

type CreateWalletAssetParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Instrument pgtype.Text    `json:"instrument"`
	Quantity   pgtype.Numeric `json:"quantity"`
}

func (q *Queries) CreateWalletAsset(ctx context.Context, arg CreateWalletAssetParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createWalletAsset, arg.UserID, arg.Instrument, arg.Quantity)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const debitWalletAsset = `-- name: DebitWalletAsset :execrows
UPDATE wallet_assets
SET
  quantity = quantity - $3,
  updated_at = now()
WHERE user_id = $1
  AND instrument = $2
  AND quantity >= $3
`

type DebitWalletAssetParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Instrument pgtype.Text    `json:"instrument"`
	Quantity   pgtype.Numeric `json:"quantity"`
}

func (q *Queries) DebitWalletAsset(ctx context.Context, arg DebitWalletAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, debitWalletAsset, arg.UserID, arg.Instrument, arg.Quantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWalletByUserId = `-- name: GetWalletByUserId :many
SELECT
  id,
  user_id,
  instrument,
  quantity,
  created_at,
  updated_at
FROM wallet_assets
WHERE user_id = $1
ORDER BY instrument
`

func (q *Queries) GetWalletByUserId(ctx context.Context, userID uuid.UUID) ([]WalletAsset, error) {
	rows, err := q.db.Query(ctx, getWalletByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletAsset
	for rows.Next() {
		var i WalletAsset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Instrument,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWallets = `-- name: ListWallets :many
SELECT
  id,
  user_id,
  instrument,
  quantity,
  created_at,
  updated_at
FROM wallet_assets
ORDER BY created_at DESC
`

func (q *Queries) ListWallets(ctx context.Context) ([]WalletAsset, error) {
	rows, err := q.db.Query(ctx, listWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletAsset
	for rows.Next() {
		var i WalletAsset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Instrument,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
